language: python

python:
  - "3.7"

cache: pip

matrix:
  include:
    - os: linux
      sudo: required
    - os: osx
      language: generic
      #env: PYTHON=3.7.5 PYTHON_CONFIGURE_OPTS="--enable-shared" HOMEBREW_NO_AUTO_UPDATE=1

#before_install: |
#  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
#    brew install pyenv-virtualenv
#    pyenv install -l
#    pyenv install $PYTHON
#    export PYENV_VERSION=$PYTHON
#    export PATH="/Users/travis/.pyenv/shims:${PATH}"
#    pyenv-virtualenv venv
#    source venv/bin/activate
#    python --version
#  fi

install:
  - pip3 install -r requirements.txt

script:
  - cd src/libs/src
  - python3 setup.py build_ext --inplace
  - mv *.so ..
  - cd ../../..
  - version=`awk '/^VERSION/{print $NF}' src/config.py | sed 's/\"//g'`
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      pyinstaller mac.spec;
      cd dist;
      npm install --global create-dmg;
      create-dmg Krait.app;
      mv "Krait 0.0.0.dmg" Krait-v${version}-macos.dmg;
    else
      pyinstaller linux.spec;
      cd dist;
      tar -czvf Krait-v${version}-linux.tar.gz Krait;
      chmod a+x ../build_rpmdeb.sh;
      ../build_rpmdeb.sh ${version};
    fi
  - ls -lh
  - cd ..
  - ls -lh

deploy:
  provider: releases
  api_key:
    secure: "ZcYEEAc6cYab6qBXV2ZlW6USOxFBp02Ltg0UZJV/44YRvA+c7oGa6CWElkd1cdejxQK3SJ7KyY8s0klvt+a1ugkeTpVucPEWTzoE/R5evTUFwsG28xzrgrEDdRZPTptXZTaZSmxdEgQn1La4xLmet58Azn4Zmn2lPtZTGRmahkaWz9TeOGSi61LIvAoj0zREyW/pW1B8nZVaCwS/7l8dyNxJIgaxxS3RpTyMNEGzpy29uHiuUJYif6THBDMB3gKbYOaX1QRm51Iy9YuC/gR3ksuSkrb18tDfOApuGyF6Nxed/34ss6ltCr5OK+Wn1f8jxF5wNSpxKqZOP5rYbeHqxa5OOYrkkrL5R8p59tTkdiNlik8K+9GVNtRychCgD/eYDs2V9eEWV82c83pIM/6bDyJlXJ8oOO5Zw7A9g3wG+kOTEbAgSbp4H/hczr8GK27XSt4q/JOspTKyd6IGUMiDC1eCFnv/znldr9q2x48/0dQwClS2Lwl+leIR6v3M54DE1EwMsc+nKFdsf8ImDFmF9z/5bboU8wB3btLE3pf8iB/+GZAzfvPaJ0ZQWdNKVmlac+1+IU+x+8Zza6xztDyIgw+C4LUGI8SKCw3eI0CG1Hrl0EW9UXVOja4rQjc75taL9A5BZBd4eA22nlRXqQtAcWEnzelB+z4CCRvqzuWTqlw="
  file_glob: true
  file: dist/Krait-v*
  skip_cleanup: true
  on:
    tags: true
