name: build

on: [push, pull_request]

jobs:
  build_installer:
    name: Build on ${{ matrix.os }}
    runs-on: ${{  matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Fix Python Compiler
        run: |
          $pydir = python -c "import sys;print(sys.exec_prefix)" | Out-String
          gendef $pydir\vcruntime140.dll
          dlltool -D $pydir\vcruntime140.dll -d vcruntime140.def -l $pydir\libs\libvcruntime140.a
          pip install pywin32
          python ci\fix_compiler_error.py
          dir $pydir\libs

      - name: Build Windows Exe
        if: runner.os == 'Windows'
        run: |
          cd src\libs\src
          python setup.py build_ext --inplace -c mingw32
          move /y *.pyd ..
          cd ..\..\..
          pyinstaller win.spec
          cd setup
          iscc win.iss
          cd ..

      - name: Upload Installer
        uses: actions/upload-artifact@v3
        with:
          name: Krait-win64
          path: setup/*.exe
