name: build

on: [push, pull_request]

jobs:
  build_installer:
    name: Build on ${{ matrix.os }}
    runs-on: ${{  matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-20.04, macos-10.15]

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Build Windows Exe
        if: runner.os == 'Windows'
        run: |
          $pydir = python -c "import sys;print(sys.exec_prefix)"
          gendef $pydir\vcruntime140.dll
          dlltool -D $pydir\vcruntime140.dll -d vcruntime140.def -l $pydir\libs\libvcruntime140.a
          pip install pywin32
          python ci\fix_compiler_error.py
          cd src\libs\src
          python setup.py build_ext --inplace -c mingw32
          mv *.pyd ..
          cd ..\..\..
          pyinstaller win.spec
          cd setup
          iscc win.iss
          cd ..

      - name: Build Linux Exe
        if: runner.os == 'Linux'
        run: |
          cd src/libs/src
          python setup.py build_ext --inplace
          mv *.so ..
          cd ../../..
          version=`awk '/^VERSION/{print $NF}' src/config.py | sed 's/\"//g'`
          pyinstaller linux.spec
          cd dist
          tar -czvf Krait-v${version}-linux.tar.gz Krait
          chmod a+x ../build_rpmdeb.sh
          ../build_rpmdeb.sh ${version}

      - name: Build MacOS Exe
        if: runner.os == 'macOS'
        run: |
          cd src/libs/src
          python setup.py build_ext --inplace
          mv *.so ..
          cd ../../..
          version=`awk '/^VERSION/{print $NF}' src/config.py | sed 's/\"//g'`
          pyinstaller mac.spec
          cd dist
          npm install --global create-dmg
          create-dmg Krait.app || true
          mv "Krait 0.0.0.dmg" Krait-v${version}-macos.dmg

      - name: Upload Installer
        uses: actions/upload-artifact@v3
        with:
          name: Krait
          path: |
            setup/*.exe
            dist/*.dmg
            dist/*.deb
            dist/*.tar.gz

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            setup/*.exe
            dist/*.dmg
            dist/*.deb
            dist/*.tar.gz
